### ISSUE TITLE
Handle `README.md` files in fuzzdb

### ISSUE THREAD

**Issue by Spellchaser** [trailofbits/protofuzz#58]
When cloning latest fuzzdb, loading mechanism fails due to `README.md` in attacks dir
<details>
  <summary>Traceback</summary>

  ```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Spellchaser/PycharmProjects/test/venv/lib/python3.7/site-packages/protofuzz/protofuzz.py", line 173, in _iteration_helper
    generator = descriptor_to_generator(self._descriptor, iter_class)
  File "/Users/Spellchaser/PycharmProjects/test/venv/lib/python3.7/site-packages/protofuzz/protofuzz.py", line 113, in descriptor_to_generator
    generator = _prototype_to_generator(descriptor, cls)
  File "/Users/Spellchaser/PycharmProjects/test/venv/lib/python3.7/site-packages/protofuzz/protofuzz.py", line 92, in _prototype_to_generator
    generator = _string_generator(descriptor)
  File "/Users/Spellchaser/PycharmProjects/test/venv/lib/python3.7/site-packages/protofuzz/protofuzz.py", line 49, in _string_generator
    vals = list(values.get_strings(max_length, limit))
  File "/Users/Spellchaser/PycharmProjects/test/venv/lib/python3.7/site-packages/protofuzz/values.py", line 23, in _limit_helper
    for value in stream:
  File "/Users/Spellchaser/PycharmProjects/test/venv/lib/python3.7/site-packages/protofuzz/values.py", line 49, in _fuzzdb_get_strings
    listing = pkg_resources.resource_listdir('protofuzz', path)
  File "/Users/Spellchaser/PycharmProjects/test/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1163, in resource_listdir
    resource_name
  File "/Users/Spellchaser/PycharmProjects/test/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1441, in resource_listdir
    return self._listdir(self._fn(self.module_path, resource_name))
  File "/Users/Spellchaser/PycharmProjects/test/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1610, in _listdir
    return os.listdir(path)
NotADirectoryError: [Errno 20] Not a directory: '/Users/Spellchaser/PycharmProjects/test/venv/lib/python3.7/site-packages/protofuzz/fuzzdb/attack/README.md'
  ```

</details>

**Comment by woodruffw** [comment]
Thanks for the report. I'll look into this.

**Comment by Spellchaser** [comment]
Oh I was gonna make a PR for a fix :)

**Comment by woodruffw** [comment]
Oh, please do!
